const products = [
  {
    _id: '1',
    name: 'MacBook APPLE PRo Touch Bar (2020) - 13,3" - Puce M1',
    image: '/images/macbook.jpeg',
    description:
      'Avec la puce Apple M1, le MacBook Pro 13 pouces atteint une vitesse et une puissance sidérantes. Il offre des performances de processeur jusqu’à 2,8 fois plus élevées. Des performances graphiques jusqu’à 5 fois plus rapides. Une vitesse d’apprentissage automatique jusqu’à 11 fois supérieure grâce à notre Neural Engine le plus avancé. Et jusqu’à 20 heures d’autonomie, un record sur Mac. C’est notre portable pro le plus apprécié, et il n’a pas fini de vous étonner.',
    brand: 'Apple',
    category: 'Ordinateur',
    price: 1399.99,
    countInStock: 4,
    rating: 5,
    numReviews: 8,
    reviews: [],
  },
  {
    name: 'Ecouteur Airpods Wireless Bluetooth',
    image: '/images/airpods.jpg',
    description:
      "La technologie Bluetooth vous permet de le connecter sans fil à des appareils compatibles Un son AAC de haute qualité offre une expérience d'écoute immersive Le microphone intégré vous permet de prendre des appels tout en travaillant.",
    brand: 'Apple',
    category: 'Musique',
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
    reviews: [],
  },
  {
    _id: '3',
    name: 'iPhone 11 Pro 256GB',
    image: '/images/phone.jpg',
    description:
      "Voici l'iPhone 11 Pro. Un système transformateur à triple caméra qui ajoute des tonnes de capacités sans complexité. Un bond sans précédent dans l'autonomie de la batterie.",
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 10,
    rating: 4,
    numReviews: 4,
    reviews: [],
  },
  {
    _id: '4',
    name: 'Apple - 11" iPad Pro (2021) WIFI 128Go - Gris Sidéral',
    image: 'images/ipadpro.jpeg',
    description:
      'L’expérience iPad ultime. Désormais avec la puce M1 et ses performances époustouflantes, un écran XDR qui laisse sans voix et une connectivité 5G fulgurante. Attachez vos ceintures.',
    brand: 'Apple',
    category: 'tablette',
    price: 899,
    countInStock: 5,
    rating: 4.5,
    numReviews: 3,
    reviews: [],
  },
  {
    _id: '5',
    name: 'Sony Playstation 4 Pro version blanche',
    image: '/images/playstation.jpg',
    description:
      "L'ultime centre de divertissement domestique commence avec PlayStation. Que vous soyez amateur de jeux, de films HD, de télévision, de musique, etc.",
    brand: 'Sony',
    category: 'console',
    price: 399.99,
    countInStock: 0,
    rating: 5,
    numReviews: 8,
    reviews: [],
  },
  {
    _id: '6',
    name: 'Apple iPhone 12 128Go, Bleu Pacifique ',
    image: 'images/iphone12.jpeg',
    description:
      'Une 5G en mode Pro. Une puce A14 Bionic qui distance nettement toutes les autres puces de smart­phone. Un système photo pro qui révolutionne la prise de vues en conditions de faible éclairage – de façon plus spectaculaire encore sur l’iPhone 12 Pro Max. Et le Ceramic Shield, qui multiplie par quatre la résistance aux chutes. La première impression est excellente. Attendez de voir la suite.',
    brand: 'Apple',
    category: 'mobiles',
    price: 1159,
    countInStock: 6,
    rating: 5,
    numReviews: 6,
    reviews: [],
  },
];
export default products;
